### PR TITLE
Add dockercloud events

### PR DESCRIPTION
**Pull request by madwire**
I have implemented dockercloud event streaming support as per #6

### CODE REVIEW

**Comment by jntullo** [comment]
Hey @madwire, thanks for your contribution! This looks great.

Don't think you meant to commit the Dockerfile to this branch, I see it's a part of your other PR.

**Comment by madwire** [comment]
Oops! sorry about that, since you have already merged that commit into master it shouldn't affect anything.

**Comment by jntullo** [comment]
I am getting a failure on the `Events API will return an Events API object`

``` bash
2) DockerCloud::Client#events Events API will return an Events API object
     Failure/Error: expect(subject).to expect(@object).to be_a DockerCloud::EventsAPI
       expected nil to be a kind of DockerCloud::EventsAPI
     # ./spec/docker_cloud_spec.rb:29:in `block (4 levels) in <top (required)>'

```

Tested with both docker compose and rake. Can you take a look?

**Comment by madwire** [comment]
@jntullo fixed

**Comment by jntullo** [comment]
awesome, thanks @madwire! 👍

**Pull request merged**
